// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/orgs": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/orgs"
                ],
                "summary": "Create an organization",
                "parameters": [
                    {
                        "description": "name (string, required)",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/store.Organization"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/admin/orgs/{orgID}": {
            "delete": {
                "description": "Permanently deletes the org and all its projects, keys, and ingest data.",
                "tags": [
                    "admin/orgs"
                ],
                "summary": "Delete an organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/orgs"
                ],
                "summary": "Rename an organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.updateOrgPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Organization"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    }
                }
            }
        },
        "/admin/orgs/{orgID}/invites": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/invites"
                ],
                "summary": "List pending invites for an organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.OrganizationInvite"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/invites"
                ],
                "summary": "Invite a user to an organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Invite payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.createInvitePayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/store.OrganizationInvite"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {}
                    }
                }
            }
        },
        "/admin/orgs/{orgID}/invites/{inviteID}": {
            "delete": {
                "tags": [
                    "admin/invites"
                ],
                "summary": "Cancel an invite",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Invite UUID",
                        "name": "inviteID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/admin/orgs/{orgID}/members": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/members"
                ],
                "summary": "List org members",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.MemberWithUser"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {}
                    }
                }
            }
        },
        "/admin/orgs/{orgID}/members/{userID}": {
            "delete": {
                "description": "Admin+. Cannot remove an owner or yourself.",
                "tags": [
                    "admin/members"
                ],
                "summary": "Remove a member from the org",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Member user UUID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    }
                }
            }
        },
        "/admin/orgs/{orgID}/members/{userID}/role": {
            "patch": {
                "description": "Owner only. Cannot change an owner's role or promote to owner.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/members"
                ],
                "summary": "Update a member's role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Member user UUID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Role payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.updateRolePayload"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    }
                }
            }
        },
        "/admin/orgs/{orgID}/projects": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/projects"
                ],
                "summary": "Lists projects in an org",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.Project"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "post": {
                "description": "Creates a tenant project scoped to the org. Requires admin role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/projects"
                ],
                "summary": "Creates a project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Project payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.createProjectPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/store.Project"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/admin/orgs/{orgID}/projects/{projectID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/projects"
                ],
                "summary": "Fetches a project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project UUID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Project"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "description": "Deletes a project and cascades to its api_keys and ingest rows.",
                "tags": [
                    "admin/projects"
                ],
                "summary": "Deletes a project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project UUID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/admin/orgs/{orgID}/projects/{projectID}/keys": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/keys"
                ],
                "summary": "Lists API keys for a project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project UUID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.APIKey"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "post": {
                "description": "Generates a new API key for a project. Plaintext key is returned ONCE. Requires admin role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/keys"
                ],
                "summary": "Creates an API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project UUID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Key payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.createKeyPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.createKeyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/admin/orgs/{orgID}/projects/{projectID}/keys/{keyID}": {
            "delete": {
                "description": "Revokes an API key. Subsequent requests using this key will return 401. Requires admin role.",
                "tags": [
                    "admin/keys"
                ],
                "summary": "Deletes an API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project UUID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Key UUID",
                        "name": "keyID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/agent/health": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rolls up run outcomes per agent_name: total runs, completion rate, loop rate, avg cost, and avg tokens over the window.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "Per-agent run-health rollup for the calling project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RFC3339, default now - 30d",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RFC3339, default now",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.RunHealthRow"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/agent/runs": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "List agent runs for the calling project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RFC3339, default now - 30d",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RFC3339, default now",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "default 25, max 1000",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "default 0",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.AgentRun"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/agent/runs/terminations": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "Run counts grouped by termination reason",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RFC3339, default now - 30d",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RFC3339, default now",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.TerminationCount"
                            }
                        }
                    }
                }
            }
        },
        "/agent/runs/timeseries": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns per-bucket run outcome counts (total, completed, failed, loop) via TimescaleDB time_bucket. bucket is one of 1h, 6h, 1d.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "Bucketed run counts over time for the calling project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RFC3339, default now - 30d",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RFC3339, default now",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "bucket size: 1h (default), 6h, 1d",
                        "name": "bucket",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.RunBucket"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/agent/runs/{runID}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "Fetch a single agent run by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent run UUID",
                        "name": "runID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RFC3339; if set, lookup is bounded to a 2s window for fast chunk pruning",
                        "name": "at",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.AgentRun"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/agent/runs/{runID}/loops": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns each tool_name + input fingerprint repeated \u003e= 2 times.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "Loop detection for an agent run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent run UUID",
                        "name": "runID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RFC3339 hint for chunk pruning",
                        "name": "at",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.LoopHit"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/agent/runs/{runID}/steps": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "List steps for an agent run, ordered by step_index asc",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent run UUID",
                        "name": "runID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RFC3339 hint for chunk pruning",
                        "name": "at",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "default 1000, max 1000",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.AgentStep"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/agent/steps/distribution": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "Step counts grouped by step_type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RFC3339, default now - 30d",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RFC3339, default now",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.StepTypeCount"
                            }
                        }
                    }
                }
            }
        },
        "/agent/summary": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "Run summary + duration percentiles for the calling project, current vs previous window",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RFC3339, default now - 30d",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RFC3339, default now",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/store.RunSummary"
                            }
                        }
                    }
                }
            }
        },
        "/agent/tools/stats": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Aggregates tool calls across every run in the window: call count, success/fail counts, success rate, and p95 latency per tool.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "Per-tool usage analytics for the calling project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RFC3339, default now - 30d",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RFC3339, default now",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.ToolStat"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/auth/invites/{token}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get invite info by token (public — for the accept page)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Invite token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.OrganizationInvite"
                        }
                    }
                }
            }
        },
        "/auth/invites/{token}/accept": {
            "put": {
                "tags": [
                    "auth"
                ],
                "summary": "Accept an invite (requires session)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Invite token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in with email + password",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.loginPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.authUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "End the current session",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get the current user and their organizations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.authUserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/auth/oauth/{provider}/callback": {
            "get": {
                "tags": [
                    "auth"
                ],
                "summary": "OAuth provider callback — issues session and redirects to dashboard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth provider (google, github)",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF state",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Temporary Redirect"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/auth/oauth/{provider}/start": {
            "get": {
                "tags": [
                    "auth"
                ],
                "summary": "Initiate OAuth login flow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth provider (google, github)",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Post-login redirect path",
                        "name": "redirect",
                        "in": "query"
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Temporary Redirect"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.registerPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.authUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/auth/verify-email/{token}": {
            "get": {
                "tags": [
                    "auth"
                ],
                "summary": "Verify email via token from the verification link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Verification token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns service status, version, and environment.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meta"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ingest/agent/runs": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Opens a new agent run record with status=\"running\". Returns id + timestamp; the client must pass both back to finish the run.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "Start an agent run",
                "parameters": [
                    {
                        "description": "Run start payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ingestAgentRunStartPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.ingestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/ingest/agent/runs/{runID}/finish": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Marks a run terminal and writes totals. timestamp must match the value returned at start (hypertable PK).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "Finish an agent run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent run UUID",
                        "name": "runID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Run finish payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ingestAgentRunFinishPayload"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/ingest/agent/steps": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Records one step in an agent loop. Server computes a SHA-256 fingerprint of tool_name + tool_input for loop detection and bumps the agent_tools registry when tool_name is present.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "Append an agent step",
                "parameters": [
                    {
                        "description": "Step payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ingestAgentStepPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.ingestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/ingest/ai": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Records one LLM call: model, token counts, cost, latency, status. project_id is derived from the API key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "Ingest an AI / LLM call trace",
                "parameters": [
                    {
                        "description": "AI trace payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ingestAIPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.ingestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/ingest/events": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Records one HTTP request: method, path, status, duration. project_id is derived from the API key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "Ingest an HTTP request event",
                "parameters": [
                    {
                        "description": "API event payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ingestEventPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.ingestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/ingest/metrics": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Records one infrastructure metric sample (cpu_percent, memory_used, etc.). project_id is derived from the API key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "Ingest a host metric",
                "parameters": [
                    {
                        "description": "Metric payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ingestMetricPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.ingestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "main.authUserResponse": {
            "type": "object",
            "properties": {
                "organizations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.Organization"
                    }
                },
                "user": {
                    "$ref": "#/definitions/store.User"
                }
            }
        },
        "main.createInvitePayload": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "member"
                    ]
                }
            }
        },
        "main.createKeyPayload": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                }
            }
        },
        "main.createKeyResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                }
            }
        },
        "main.createProjectPayload": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                }
            }
        },
        "main.ingestAIPayload": {
            "type": "object",
            "required": [
                "model",
                "status"
            ],
            "properties": {
                "agent_run_id": {
                    "type": "string"
                },
                "cost_usd": {
                    "type": "number",
                    "minimum": 0
                },
                "error_message": {
                    "type": "string",
                    "maxLength": 2000
                },
                "input_tokens": {
                    "type": "integer",
                    "minimum": 0
                },
                "latency_ms": {
                    "type": "integer",
                    "minimum": 0
                },
                "metadata": {
                    "type": "object"
                },
                "model": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1
                },
                "output_tokens": {
                    "type": "integer",
                    "minimum": 0
                },
                "provider": {
                    "type": "string",
                    "maxLength": 50
                },
                "request_id": {
                    "type": "string",
                    "maxLength": 200
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "success",
                        "error",
                        "timeout"
                    ]
                },
                "timestamp": {
                    "type": "string"
                },
                "total_tokens": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "main.ingestAgentRunFinishPayload": {
            "type": "object",
            "required": [
                "status",
                "timestamp"
            ],
            "properties": {
                "duration_ms": {
                    "type": "integer",
                    "minimum": 0
                },
                "loop_detected": {
                    "type": "boolean"
                },
                "loop_step_index": {
                    "type": "integer",
                    "minimum": 0
                },
                "output": {
                    "type": "string",
                    "maxLength": 100000
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "completed",
                        "failed"
                    ]
                },
                "termination_reason": {
                    "type": "string",
                    "enum": [
                        "clean",
                        "max_steps_reached",
                        "context_limit",
                        "error",
                        "loop_detected",
                        "timeout"
                    ]
                },
                "timestamp": {
                    "type": "string"
                },
                "total_cost_usd": {
                    "type": "number",
                    "minimum": 0
                },
                "total_steps": {
                    "type": "integer",
                    "minimum": 0
                },
                "total_tokens": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "main.ingestAgentRunStartPayload": {
            "type": "object",
            "required": [
                "agent_name"
            ],
            "properties": {
                "agent_name": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1
                },
                "input": {
                    "type": "string",
                    "maxLength": 10000
                },
                "metadata": {
                    "type": "object"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "main.ingestAgentStepPayload": {
            "type": "object",
            "required": [
                "agent_run_id",
                "step_type"
            ],
            "properties": {
                "agent_run_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string",
                    "maxLength": 100000
                },
                "cost_usd": {
                    "type": "number",
                    "minimum": 0
                },
                "metadata": {
                    "type": "object"
                },
                "step_index": {
                    "type": "integer",
                    "minimum": 0
                },
                "step_type": {
                    "type": "string",
                    "enum": [
                        "think",
                        "tool_call",
                        "tool_result",
                        "replan"
                    ]
                },
                "timestamp": {
                    "type": "string"
                },
                "tokens": {
                    "type": "integer",
                    "minimum": 0
                },
                "tool_input": {
                    "type": "object"
                },
                "tool_latency_ms": {
                    "type": "integer",
                    "minimum": 0
                },
                "tool_name": {
                    "type": "string",
                    "maxLength": 200
                },
                "tool_output": {
                    "type": "object"
                },
                "tool_success": {
                    "type": "boolean"
                }
            }
        },
        "main.ingestEventPayload": {
            "type": "object",
            "required": [
                "duration_ms",
                "method",
                "path",
                "service",
                "status_code"
            ],
            "properties": {
                "duration_ms": {
                    "type": "integer",
                    "minimum": 0
                },
                "error": {
                    "type": "string",
                    "maxLength": 2000
                },
                "ip": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object"
                },
                "method": {
                    "type": "string",
                    "enum": [
                        "GET",
                        "POST",
                        "PUT",
                        "PATCH",
                        "DELETE",
                        "OPTIONS",
                        "HEAD"
                    ]
                },
                "path": {
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 1
                },
                "request_size_bytes": {
                    "type": "integer",
                    "minimum": 0
                },
                "response_size_bytes": {
                    "type": "integer",
                    "minimum": 0
                },
                "service": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "status_code": {
                    "type": "integer",
                    "maximum": 599,
                    "minimum": 100
                },
                "timestamp": {
                    "type": "string"
                },
                "user_agent": {
                    "type": "string",
                    "maxLength": 500
                }
            }
        },
        "main.ingestMetricPayload": {
            "type": "object",
            "required": [
                "host",
                "metric_name",
                "value"
            ],
            "properties": {
                "host": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1
                },
                "labels": {
                    "type": "object"
                },
                "metric_name": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1
                },
                "timestamp": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "main.ingestResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "main.loginPayload": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "main.registerPayload": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 255
                },
                "name": {
                    "type": "string",
                    "maxLength": 100
                },
                "password": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 8
                }
            }
        },
        "main.updateOrgPayload": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                }
            }
        },
        "main.updateRolePayload": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "member"
                    ]
                }
            }
        },
        "store.APIKey": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_used_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                }
            }
        },
        "store.AgentRun": {
            "type": "object",
            "properties": {
                "agent_name": {
                    "type": "string"
                },
                "duration_ms": {
                    "type": "integer"
                },
                "finished_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "input": {
                    "type": "string"
                },
                "loop_detected": {
                    "type": "boolean"
                },
                "loop_step_index": {
                    "type": "integer"
                },
                "metadata": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "output": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "termination_reason": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "total_cost_usd": {
                    "type": "number"
                },
                "total_steps": {
                    "type": "integer"
                },
                "total_tokens": {
                    "type": "integer"
                }
            }
        },
        "store.AgentStep": {
            "type": "object",
            "properties": {
                "agent_run_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "cost_usd": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "input_fingerprint": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "metadata": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "project_id": {
                    "type": "string"
                },
                "step_index": {
                    "type": "integer"
                },
                "step_type": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "tokens": {
                    "type": "integer"
                },
                "tool_input": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "tool_latency_ms": {
                    "type": "integer"
                },
                "tool_name": {
                    "type": "string"
                },
                "tool_output": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "tool_success": {
                    "type": "boolean"
                }
            }
        },
        "store.LoopHit": {
            "type": "object",
            "properties": {
                "fingerprint": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "hits": {
                    "type": "integer"
                },
                "step_indices": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "tool_name": {
                    "type": "string"
                }
            }
        },
        "store.MemberWithUser": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organization_id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "store.Organization": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "store.OrganizationInvite": {
            "type": "object",
            "properties": {
                "accepted_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "organization_id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "store.Project": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organization_id": {
                    "type": "string"
                }
            }
        },
        "store.RunBucket": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "completed": {
                    "type": "integer"
                },
                "failed": {
                    "type": "integer"
                },
                "loop": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "store.RunHealthRow": {
            "type": "object",
            "properties": {
                "agent_name": {
                    "type": "string"
                },
                "avg_cost_usd": {
                    "type": "number"
                },
                "avg_tokens": {
                    "type": "number"
                },
                "completed_runs": {
                    "type": "integer"
                },
                "completion_rate": {
                    "type": "number"
                },
                "loop_rate": {
                    "type": "number"
                },
                "loop_runs": {
                    "type": "integer"
                },
                "prev_total_runs": {
                    "type": "integer"
                },
                "total_runs": {
                    "type": "integer"
                }
            }
        },
        "store.RunSummary": {
            "type": "object",
            "properties": {
                "avg_cost_usd": {
                    "type": "number"
                },
                "avg_tokens": {
                    "type": "number"
                },
                "completed_runs": {
                    "type": "integer"
                },
                "completion_rate": {
                    "type": "number"
                },
                "duration_p50_ms": {
                    "type": "integer"
                },
                "duration_p95_ms": {
                    "type": "integer"
                },
                "duration_p99_ms": {
                    "type": "integer"
                },
                "loop_rate": {
                    "type": "number"
                },
                "loop_runs": {
                    "type": "integer"
                },
                "total_runs": {
                    "type": "integer"
                },
                "total_steps": {
                    "type": "integer"
                },
                "total_tool_calls": {
                    "type": "integer"
                },
                "unique_agents": {
                    "type": "integer"
                },
                "unique_tools": {
                    "type": "integer"
                }
            }
        },
        "store.StepTypeCount": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "step_type": {
                    "type": "string"
                }
            }
        },
        "store.TerminationCount": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "termination_reason": {
                    "type": "string"
                }
            }
        },
        "store.ToolStat": {
            "type": "object",
            "properties": {
                "call_count": {
                    "type": "integer"
                },
                "fail_count": {
                    "type": "integer"
                },
                "is_new": {
                    "type": "boolean"
                },
                "p50_latency_ms": {
                    "type": "integer"
                },
                "p95_latency_ms": {
                    "type": "integer"
                },
                "p99_latency_ms": {
                    "type": "integer"
                },
                "prev_call_count": {
                    "type": "integer"
                },
                "success_count": {
                    "type": "integer"
                },
                "success_rate": {
                    "type": "number"
                },
                "tool_name": {
                    "type": "string"
                }
            }
        },
        "store.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_verified": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "verified_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Format: \"Bearer kw_\u003ctoken\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Keelwave API",
	Description:      "Unified observability platform for AI agents, APIs, and infrastructure.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
