import { createOctokit } from './client';

export interface Update {
  depName: string;
  currentVersion: string;
  newVersion: string;
  cveId: string;
  reason: string;
}

async function parseRepo(repo: string): Promise<{ owner: string; repo: string }> {
  const parts = repo.split('/');
  if (parts.length !== 2 || !parts[0] || !parts[1]) {
    throw new Error(`Invalid repo format: "${repo}". Expected owner/repo`);
  }
  return { owner: parts[0], repo: parts[1] };
}

export async function createBranch(
  token: string,
  repo: string,
  branchName: string,
  baseSha: string,
): Promise<void> {
  const { owner, repo: repoName } = await parseRepo(repo);
  const octokit = createOctokit(token);

  await octokit.request('POST /repos/{owner}/{repo}/git/refs', {
    owner,
    repo: repoName,
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  });
}

export async function getFileSha(
  token: string,
  repo: string,
  path: string,
  ref?: string,
): Promise<string | null> {
  const { owner, repo: repoName } = await parseRepo(repo);
  const octokit = createOctokit(token);

  try {
    const res = await octokit.request('GET /repos/{owner}/{repo}/contents/{path}', {
      owner,
      repo: repoName,
      path,
      ref,
    });
    return (res.data as { sha?: string }).sha ?? null;
  } catch (err: unknown) {
    if ((err as { status?: number }).status === 404) return null;
    throw err;
  }
}

export async function commitFile(
  token: string,
  repo: string,
  branchName: string,
  path: string,
  content: string,
  sha: string,
): Promise<string> {
  const { owner, repo: repoName } = await parseRepo(repo);
  const octokit = createOctokit(token);

  const encoded = Buffer.from(content).toString('base64');

  const res = await octokit.request('PUT /repos/{owner}/{repo}/contents/{path}', {
    owner,
    repo: repoName,
    path,
    message: `fix: bump ${path} to safe version`,
    content: encoded,
    branch: branchName,
    sha,
  });

  return (res.data as { commit?: { sha?: string } }).commit?.sha ?? sha;
}

export async function createGitHubPr(
  token: string,
  repo: string,
  updates: Update[],
): Promise<string> {
  const { owner, repo: repoName } = await parseRepo(repo);
  const octokit = createOctokit(token);

  const validateRes = await octokit.request('GET /repos/{owner}/{repo}', { owner, repo: repoName });

  const defaultBranch = (validateRes.data as { default_branch?: string }).default_branch ?? 'main';

  const packageJsonPath = 'package.json';
  const existingSha = await getFileSha(token, repo, packageJsonPath, defaultBranch);

  if (!existingSha) {
    throw new Error(`package.json not found on ${defaultBranch} branch`);
  }

  const getRes = await octokit.request('GET /repos/{owner}/{repo}/contents/{path}', {
    owner,
    repo: repoName,
    path: packageJsonPath,
    ref: defaultBranch,
  });

  const fileData = getRes.data as { content?: string };
  const fileContent = fileData.content
    ? Buffer.from(fileData.content, 'base64').toString('utf-8')
    : '{}';

  let pkg: Record<string, unknown>;
  try {
    pkg = JSON.parse(fileContent) as Record<string, unknown>;
  } catch {
    pkg = {};
  }

  const deps = (pkg.dependencies as Record<string, string> | undefined) ?? {};
  const devDeps = (pkg.devDependencies as Record<string, string> | undefined) ?? {};

  for (const u of updates) {
    if (deps[u.depName] !== undefined) {
      deps[u.depName] = u.newVersion;
    } else if (devDeps[u.depName] !== undefined) {
      devDeps[u.depName] = u.newVersion;
    }
  }

  pkg.dependencies = deps;
  pkg.devDependencies = devDeps;

  const timestamp = Date.now();
  const branchName = `vigilops/fix-${updates[0]?.cveId ?? 'update'}-${timestamp}`;

  await createBranch(
    token,
    repo,
    branchName,
    (validateRes.data as { default_branch?: string }).default_branch ?? 'main',
  );

  await commitFile(
    token,
    repo,
    branchName,
    packageJsonPath,
    JSON.stringify(pkg, null, 2),
    existingSha,
  );

  const bodyLines = [
    '## VigilOps Auto-Fix PR',
    '',
    'This PR bumps the following dependencies to safe versions:',
    '',
    ...updates.map((u) => `- **${u.depName}**: ${u.currentVersion} → ${u.newVersion} (${u.cveId})`),
    '',
    '### Why these changes?',
    ...updates.map((u) => `- ${u.reason}`),
    '',
    '_Generated by [VigilOps](https://vigilops.dev) — vulnerability scanning and auto-fix._',
  ];

  const prRes = await octokit.request('POST /repos/{owner}/{repo}/pulls', {
    owner,
    repo: repoName,
    title: `fix: bump ${updates.map((u) => u.depName).join(', ')} to safe versions`,
    body: bodyLines.join('\n'),
    head: branchName,
    base: defaultBranch,
  });

  return (prRes.data as { html_url?: string }).html_url ?? '';
}
